version: '3'

services:
  web:
    build: 
      context: .
      args:
        YARN_VERSION: ${YARN_VERSION}
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '3000:3000'
    volumes:
      - '.:/app'
    tty: true
    stdin_open: true
    depends_on:
      - db
    links: 
      - db

  db:
    image: postgres:12
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - 'db-data:/var/lib/postgresql/12/data'

volumes:
  db-data: